### ISSUE TITLE
which version of matlab should be used?

### ISSUE THREAD

**Issue by AllenQin84** [borgestassio/5MW-NREL-Controllers---Simulink#1]
Hi borg,
Firstly, thanks for sharing your model.But it doesn't work on my laptop which installed matlab 2016b.
The error information as follow:
![image](https://user-images.githubusercontent.com/42942011/50219470-46f13200-03ca-11e9-96b8-2443a326249e.png)

Could you please have a look at it?

**Comment by borgestassio** [comment]
I'm sorry for the late reply. Didn't check this project for a while.

The Matblab version used is Matlab R20017b
